// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edhwvotqagnrjqfncojq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkaHd2b3RxYWducmpxZm5jb2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzIzODEsImV4cCI6MjA2OTAwODM4MX0.2QJRmzg3cLpAbGAHlfEmCxIMZzIQUa41gmUQIiBf96k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});